<a href="https://colab.research.google.com/github/DaxPatel10/DATA-SCIENSE/blob/main/array_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

indexing and slicing of vectors


In [2]:
import numpy as np

In [5]:
arr = np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [6]:
arr[5]

np.int64(16)

In [7]:
arr[1:5]

array([12, 13, 14, 15])

numpy indexing abd slicing of matrix


In [9]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [7]:
import numpy as np
arr = np.arange(1,31).reshape(6,5)
arr[0,0,]
arr[5,2]

np.int64(28)

In [8]:
slice1 = arr[3:5,2:4]
print(slice)

<class 'slice'>


In [9]:
slice1 = arr[3:6,3:5]
print(slice)

<class 'slice'>


boolen indexing

In [10]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
bool_index = arr %2 ==0
print(bool_index)

[False  True False  True False  True False  True False  True]


In [12]:
arr = arr[bool_index]
print(arr)

[ 2  4  6  8 10]


operations


In [13]:
import numpy as np

In [14]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

a1 + a2

array([ 7,  9, 11, 13, 15])

In [15]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

broadcasting

In [54]:
import numpy as np

In [56]:
l = [10,20,30,40]
arr = np.array(l)

In [58]:
arr + 10


array([20, 30, 40, 50])

deep AND shallow copy

In [72]:
arr = np.arange(1,11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [78]:
slice1 = arr[:5]
slice1 = slice1*10
slice1

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60]],

       [[ 70,  80],
        [ 90, 100],
        [110, 120]],

       [[130, 140],
        [150, 160],
        [170, 180]]])

In [63]:
arr = np.arange(1,19).reshape(3,3,2)

In [57]:
arr[2,2]


array([17, 18])

In [58]:
result = np.array([arr[i,i] for i in range(3)])

In [59]:
result

array([[ 1,  2],
       [ 9, 10],
       [17, 18]])