<a href="https://colab.research.google.com/github/DaxPatel10/DATA-SCIENSE/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

In [ ]:
arr = np.linspace (1,5,5)
print(arr)

[1. 2. 3. 4. 5.]


        random genration function

In [ ]:
np.random.rand (10)

array([0.64978724, 0.40484541, 0.86539629, 0.94397266, 0.34071245,
       0.88166553, 0.21019795, 0.03535833, 0.31388481, 0.95060846])

In [ ]:
np.random.randn(5)

array([ 0.51736302, -1.01776179, -0.03240277, -1.07725401,  0.05297396])

In [ ]:
np.random.randint(5,11111111111,5)

array([ 1039849020, 10035258815,  1175814887,  9854992618,  3352763163])

array attributes

In [ ]:
arr = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

arr methos


In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis =0)

array([12, 15, 18])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.argmax()

np.int64(8)

reshaping and resizing

In [ ]:
arr = np.arange(1,10)
print(arr )


[1 2 3 4 5 6 7 8 9]


In [ ]:
arr = arr.reshape(3,3)

In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
